node_module(
  name='js-module',
  package_name='webpack-example',
  build_script='wp',
  output_dir='dist',
  scope='forced',
  sources=rglobs(
    'index.js',
    'npm-shrinkwrap.json',
    'package.json',
    'webpack.config.js',
  )
)

